# Generated by Django 2.0.13 on 2019-03-03 06:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
